# Compliance matrix data — JCDC TBE-034 line items vs Abatis Praesidium Suite
# Status codes: C = Comply (covered, named component)
#               N = Comply as Noted (deviation already declared by 4S in TBE-034)
#               A = Action for V2 (capability exists but must be named/documented in V2 plan)
#               G = Gap (needs product decision or formally negotiated deviation)

MATRIX = [
{
 "item": "1.1", "title": "Network Detection & Response (NDR)",
 "specrefs": "272111 §1.8-C Network Security · 272541 §1.8-I Data Leak Prevention · 272541 §1.8-O Cyber Security Tools · 270501 §2.8-B NDR/EDR Tools",
 "rows": [
  (1, "Detection of threats in real time across the network",
      "Zeek sensor grid (2 per site) on passive network TAPs at both data centres and edge locations; events stream to the Wazuh analysis cluster in near-real-time",
      "C", "V2 documents sensor placement per network segment: external links, each VLAN vertical, wireless, critical systems, each DMZ (per 272541 2.10.B.13.o)"),
  (2, "Machine-learning analysis of network traffic, incl. malware detection in encrypted traffic (without decryption) and distributed anomaly detection",
      "ntopng Encrypted Traffic Analysis — JA3/JA3S TLS fingerprinting, SNI and certificate analytics with no session termination — plus RITA behavioural analysis (beaconing detection, DNS-tunnelling analysis, entropy scoring, C2 behaviour); Wazuh correlates across both sites for distributed anomaly detection",
      "C", "Components named in Architecture Overview v2.1 — V2 plan carries the identical names so TBE-034, the overview and the plan agree"),
  (3, "Behavioral analytics tool to identify abnormal activity constituting a security breach",
      "RITA behavioural analysis over Zeek logs (beaconing, tunnelling, entropy) + Wazuh behavioural rulesets on endpoint and network telemetry",
      "C", "Use-case catalogue (watchlists, baselines) delivered at commissioning"),
  (4, "Monitor and control the movement of sensitive information across data networks",
      "ntopng nDPI flow inspection (300+ application protocols) detects unauthorised uploads, tunnels and egress anomalies; ELK correlates live flows against OpenMetadata sensitivity tags (e.g. PII-tagged database exfiltrating); Shuffle SOAR enforces — perimeter block or host isolation",
      "C", "Control = automated containment via SOAR playbook; V2 lists the approved auto-block classes agreed with the SOC"),
  (5, "Use a specific network appliance or embedded technology to selectively capture and analyze traffic",
      "Dedicated Zeek sensor appliances fed by passive optical TAPs; selective capture policies per segment",
      "C", ""),
  (6, "Passively monitor traffic, recognise the data stream, assemble packets, reconstruct the carried file and perform analysis",
      "Native Zeek capability: passive stream reassembly and file reconstruction (files.log + extracted-file analysis pipeline to Wazuh/YARA)",
      "C", "Direct match to Zeek's file analysis framework — state this explicitly in V2"),
  (7, "Alert and optionally block the data flow in real time based on a defined rule set",
      "Real-time alerting via Wazuh; automated blocking via Shuffle SOAR playbooks — IP block at the perimeter firewall, host isolation, session teardown — executed in seconds without waiting on an analyst",
      "C", "V2 documents the firewall-integration API (CHEC's firewall vendor) and the playbook catalogue"),
  (8, "Seamless integration with SIEM",
      "Zeek logs ship natively (JSON) via Filebeat into the Wazuh indexer; single correlation plane",
      "C", ""),
 ],
},
{
 "item": "1.3", "title": "Security Information & Event Management (SIEM)",
 "specrefs": "270501 §2.8 · 272541 §2.11 SIEM Functionality · 272541 §1.8-G Incident Mgmt · §1.8-H Event Monitoring · 272111 p30 §12",
 "rows": [
  (1, "Threat hunting — capability to hunt for threats that have not triggered alarms",
      "Wazuh + OpenSearch ad-hoc hunting queries over full raw event store (120-day online); saved hunting dashboards and MITRE ATT&CK mapping",
      "C", ""),
  (2, "Monitoring user activity and behavioural analytics",
      "Windows Security/PowerShell/auditd telemetry per endpoint; Wazuh logon and privilege-use analytics; per-user timelines",
      "C", ""),
  (3, "Responding to incidents: alerting, quarantining, isolating, remediating",
      "Wazuh detects → DFIR-IRIS documents → Shuffle SOAR acts: predefined playbooks isolate the endpoint, block the C2 IP at the firewall, suspend the account and retrieve forensic artefacts within seconds; every action logged back to IRIS",
      "C", "This trio is the explicit SOAR answer for 272541 §1.8-O; per the integration paper, actions run in parallel with the analyst investigation"),
  (4, "Assess effectiveness of security controls via comprehensive reporting and analytics",
      "Wazuh compliance and detection-coverage dashboards; DFIR-IRIS case KPIs (MTTD/MTTR per incident class)",
      "C", ""),
  (5, "High-performance capabilities for real-time monitoring, analysis and response",
      "4-node Wazuh manager cluster (2 per site) + OpenSearch indexer tier; engineered to ≤3 s event-to-console (272541 §1.8-L.2)",
      "A", "V2 publishes the sizing calculation: sustained/peak EPS, indexer node count, storage per retention tier — replacing the undersized figures in V1"),
  (6, "Integration with threat-intelligence feeds and databases",
      "MISP threat-intelligence platform (per site, replicated) feeding Wazuh CDB lists and rules; Shuffle playbooks enrich alerts from TI platforms; DXI honeynet option captures full kill-chain TTPs/IOCs for empirical, project-specific intelligence",
      "A", "MISP formally added to the V2 bill of materials — the spec requires a deployed intelligence platform with JCDC use cases and watchlists (272541 §1.8-H.7.a)"),
  (7, "Collect data from syslog, files, servers, network devices, firewalls, logs and more",
      "Wazuh agents (servers/endpoints) + agentless syslog intake via the aggregator tier for network devices, firewalls and appliances",
      "C", ""),
  (8, "Conduct forensic analysis for incidents",
      "Wazuh full event store + Zeek network history + DFIR-IRIS evidence handling and chain-of-custody",
      "N", "Deviation declared in TBE-034: 'Dependent on forensic tooling… additional toolsets may be required for attribution, e.g. identifying bad actors.' V2 restates this verbatim"),
  (9, "API integration with threat-intelligence services for up-to-date IOC feeds",
      "MISP feed API → Wazuh API pipeline; automatic IOC list refresh",
      "A", "Named and diagrammed in V2 alongside item 6"),
  (10, "API integration with security devices for automated response capabilities",
      "Wazuh Active Response API integrations: perimeter firewalls (block), endpoints (isolate), AD (disable account)",
      "C", "Integration inventory table in V2"),
  (11, "Ad-hoc search and reporting of breaches",
      "OpenSearch query interface + scheduled/exportable breach reports",
      "C", ""),
  (12, "Track attackers' actions",
      "Cross-source timeline reconstruction (endpoint + network + application) in DFIR-IRIS casework",
      "C", ""),
  (13, "Establish a tool for penetration testing",
      "SIEM provides legally admissible logging with chain of custody validating PT exercises; independent qualified third parties conduct the PT itself",
      "N", "Deviation declared in TBE-034 (independent third-party PT). V2 adds the vulnerability-scanning tool (item 14) as the in-scope testing instrument"),
  (14, "Analyze, test, track and record vulnerability reports",
      "Wazuh Vulnerability Detection module (CVE correlation against installed-package inventory, all agents) + OpenVAS scanner for application/network scanning; findings tracked in DFIR-IRIS",
      "C", "Both tools named in V2 bill of materials"),
  (15, "Collect security event reports from constituents, vendors, security organizations and automated sensors",
      "DFIR-IRIS intake channels (manual reports, vendor advisories) + automated sensor feeds via Wazuh",
      "C", ""),
  (16, "Work with vulnerability-management tools to prioritize detected vulnerabilities",
      "Wazuh VD severity/CVSS scoring merged with asset-criticality tags for prioritised remediation queues",
      "C", ""),
  (17, "Protect sensitive security data (login credentials, PII) within the SIEM",
      "Role-based access control, MFA on consoles, field-level anonymisation options, encrypted storage",
      "A", "V2 documents RBAC model and encryption-at-rest configuration for the indexer tier"),
  (18, "Support data encryption; integrate seamlessly with firewalls and IDS/IPS",
      "TLS 1.2+ on all agent→manager and inter-node channels; indexer encryption at rest; firewall and IDS/IPS log/response integration",
      "C", ""),
 ],
},
{
 "item": "1.4", "title": "Syslog Server",
 "specrefs": "272541 §1.8-H Event Monitoring · 272111 p30 §11 · 272111 §1.2 Summary",
 "rows": [
  (1, "Customisable log-rotation policies and data-retention periods",
      "Syslog aggregator tier (2 per site) with policy-driven rotation and archiving per source class",
      "C", ""),
  (2, "Real-time monitoring of logs; notify IT administrators of critical events",
      "Aggregators forward in real time to Wazuh; alerting via email/SMS-capable channels per 272541 §1.8-E.10",
      "C", ""),
  (3, "Ensure collection of all data about information system, service and network, stored and processed",
      "All infrastructure and security devices point to the aggregator VIP (round-robin DNS across sites); collection completeness audited monthly",
      "C", ""),
  (4, "Integrate with other security tools such as SIEM",
      "Native forwarding into Wazuh indexer",
      "C", ""),
  (5, "Filtering of logs",
      "Per-source filter policies on the aggregator tier (severity, facility, pattern)",
      "C", ""),
  (6, "Detection and alerting of anomalous/suspicious/malicious activities via syslog alerts, incl. alerts on specific log events or patterns",
      "Pattern- and event-based alert rules in Wazuh applied to the syslog stream",
      "C", ""),
  (7, "Retention of log data: 3 months",
      "120 days online (30 days hot + 90 days warm) — exceeds the 3-month requirement; archive tier beyond",
      "C", "State the arithmetic explicitly in V2"),
  (8, "Report system performance, security incidents and log-data trends to help IT make informed decisions",
      "Trend dashboards (volume, source health, incident rates) in the Wazuh console",
      "C", ""),
 ],
},
{
 "item": "1.5", "title": "Endpoint Security & Data Leak Prevention (EDR / DLP)",
 "specrefs": "272111 p32 §17 End Point Security · 272541 §1.8-B Server/Application Security · §1.8-I DLP · §1.8-O Tools · 270501 §2.8-B · 270501 §2.2-I",
 "rows": [
  (1, "Real-time monitoring and detection of threats across endpoints, with real-time notifications and configurable alerts",
      "Abatis HDF/DXI enforces execution control in real time at the kernel; every block/attempt event raised instantly to CMC; Wazuh agent adds telemetry-based detection with configurable alert rules",
      "C", ""),
  (2, "Behavioural analytics: identify abnormal activity that may constitute a security breach",
      "Wazuh endpoint behavioural rules (process lineage, persistence attempts, anomalous logons); DXI blocked-execution events are themselves high-fidelity breach indicators",
      "C", ""),
  (3, "Responding to incidents: alerting, quarantining, isolating, remediating",
      "Shuffle SOAR playbooks (host isolation, process kill, account disable) triggered by Wazuh detections; DXI default-deny has already contained payload execution pre-incident",
      "C", ""),
  (4, "Perform forensic analysis on endpoints, including file and memory analysis",
      "Forensic-grade execution and file-integrity logs; deep file/memory forensics via DFIR toolset on demand",
      "N", "Deviation declared in TBE-034: 'Limited; while it can generate forensic logs, its primary focus is on prevention rather than detailed forensic analysis.' V2 restates verbatim"),
  (5, "Seamless integration with SIEM",
      "CMC and Wazuh agent events natively unified in the Wazuh indexer",
      "C", ""),
  (6, "Visibility of endpoint devices: processes, files, registry keys, network connections",
      "Wazuh syscollector (process, package, port and network inventory) + FIM incl. Windows registry monitoring",
      "C", ""),
  (7, "Advanced scanning and detection against malware incl. viruses, Trojans and keyloggers",
      "DXI default-deny neutralises any unauthorised executable — including trojans, droppers and keylogger binaries — without needing a signature; complemented by Wazuh YARA/CDB malware scanning for files at rest",
      "A", "V2 must state the anti-malware position explicitly (execution allowlisting as primary control + scanner as complement) to pre-empt the 'where is the AV?' question against 272541 §1.8-B.2"),
  (8, "Encryption at the endpoint: end-to-end encryption of data at rest, in transport and on the endpoint",
      "OS-native full-disk encryption managed centrally: BitLocker via GPO (Windows), LUKS (Linux); TLS for data in transit",
      "N", "Deviation declared in TBE-034 (relies on OS-native encryption). V2 adds central key-escrow/management via AD to strengthen the answer"),
  (9, "Mobile security: encryption, anti-malware and web protection for mobile devices",
      "Not in current Praesidium scope",
      "G", "Answered 'Comply' in TBE-034. Options: add an MDM/mobile-security component to scope, assign to another package via demarcation, or negotiate formal deviation — decide before V2 issues"),
  (10, "User control: control over installation and modification of applications and the operating system",
      "Core DXI function: only approved executables can install or run; OS and application change control enforced at the kernel",
      "C", "Strongest single line in the offer — lead with it"),
  (11, "Automatically address breaches by isolating infected systems and blocking communication between them",
      "Shuffle SOAR automated host isolation and inter-host block (no human validation needed for predefined threat categories); DXI prevents lateral-movement tooling from executing at all",
      "C", ""),
  (12, "Multi-platform support: Windows, macOS, Android and iOS",
      "Windows and Linux fully covered (DXI + Wazuh); macOS: Wazuh agent available, DXI coverage to be confirmed; Android/iOS: not covered",
      "G", "Same decision as item 9 — mobile/macOS scope must be resolved (MDM addition, demarcation, or deviation)"),
  (13, "Automated software updates: endpoints always protected by automatically updating software and protection mechanisms",
      "Agent updates via SCCM (Windows) and Ansible (Linux); DXI requires no signature updates by design — protection does not age",
      "C", ""),
  (14, "Utilize a single-agent deployment strategy to simplify installation, updates and maintenance",
      "Single deployment package per platform (SCCM application / Ansible role) installs the full endpoint stack; DXI is a ~100 KB kernel driver with no runtime maintenance",
      "A", "Two lightweight components deploy as one package — V2 justifies against the single-agent intent (simplicity of install/update/maintenance) rather than literal agent count"),
  (15, "Security threat intelligence: identify and respond to evolving threats using advanced analytics and TI feeds",
      "MISP TI platform feeding endpoint detection rules and IOC lists; Shuffle playbooks enrich every alert with TI context; optional DXI honeynet deployment captures full kill-chains for project-specific TTP/IOC intelligence and attribution",
      "A", "Named in V2 alongside SIEM items 6/9"),
  (16, "Advanced email protection: secure communication with attachments; identify and block malicious emails",
      "Not in current Praesidium scope",
      "G", "Answered 'Comply' in TBE-034. Resolve via scope demarcation (email security typically sits with the messaging package) or add a mail-gateway component; DXI does neutralise weaponised attachments at execution time — state as mitigating layer, not substitute"),
  (17, "Centralized management and reporting: manage, configure and monitor endpoint security from a single location",
      "CMC as the single policy console for all 150k endpoints; Wazuh as the single monitoring pane (all telemetry converges there); IRIS as the single incident record — each HA across the two sites",
      "A", "V2 describes the console operating model (policy / monitoring / casework) and the SOC workflow between them, per the integration paper"),
  (18, "Advanced threat prevention: proactively identify and prevent potential security threats",
      "Default-deny execution control is proactive prevention by construction — threats are blocked before execution, not detected after",
      "C", ""),
  (19, "In addition to signature-based detection mechanisms, machine learning applied to detect and block new and emerging threats",
      "DXI blocks new and emerging executables without signatures — deterministic default-deny remains effective even against AI-generated malware; Wazuh XDR behavioural baselines (users, endpoints, applications) flag deviations, with automated threat hunts across the 120-day store",
      "C", "Positioning per the XDR function paper: prevention by authorisation + behavioural analytics exceeds the clause's intent of catching unknown threats"),
  (20, "Performing security patches and upgrades",
      "WSUS/SCCM patch management integrated; DXI protects unpatched and legacy systems in the interim (relevant for RTOS/OT)",
      "C", ""),
  (21, "Vulnerability management, incl. security updates and patching for vulnerable systems",
      "Wazuh Vulnerability Detection (continuous CVE correlation) driving the WSUS/SCCM patch queues",
      "C", ""),
  (22, "Provide vulnerability assessment and security testing tool(s) for applications",
      "Wazuh SCA (configuration assessment) + OpenVAS application/network scanning",
      "A", "OpenVAS (or agreed equivalent) added to V2 bill of materials"),
  (23, "Monitor and control the movement of sensitive information on the end-use system",
      "Network-side movement fully covered (ntopng + OpenMetadata tags correlated in ELK, Shuffle enforcement); on-device movement monitored via Wazuh (removable-media and file events) — content-aware on-device control not yet named",
      "G", "The remaining DLP gap is device-level control only (see item 26). Decide: endpoint-DLP agent addition, demarcation, or negotiated deviation scoped to on-device control"),
  (24, "Ability to seek out and identify files (sensitive-data discovery at rest)",
      "OpenMetadata automated asset discovery and classification — continuous crawlers tag PII / financial / confidential data across SQL databases, warehouses and object storage; lineage tracking maps where tagged data flows",
      "A", "Per the DLP function paper. V2 confirms coverage scope for unstructured file shares alongside structured repositories"),
  (25, "Ability to open the file and scan the specific content",
      "OpenMetadata classification models and pattern matching scan schema, column and content patterns to assign sensitivity tags; policy violations flagged when tagged data reaches non-compliant destinations",
      "A", "Same scope confirmation as item 24"),
  (26, "Control copying data to thumb drives, sending to printers, and cut-and-paste between applications",
      "DXI blocks unauthorised executables launched from removable media; Wazuh logs USB/device events; content-aware device control (USB write / print / clipboard) not yet named",
      "G", "The one open DLP decision — endpoint device-control component, demarcation, or deviation; items 23/26 resolve together"),
 ],
},
]

STATUS = {
 "C": ("Comply", "st-c"),
 "N": ("Comply as Noted", "st-n"),
 "A": ("Action for V2", "st-a"),
 "G": ("Gap — decide", "st-g"),
}
